name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 1.8
      uses: actions/setup-java@v4
      with:
        java-version: '1.8'
        distribution: 'temurin'

    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1.7.2
      
    - name: Setup gradlew
      run: chmod +x gradlew

    - name: Execute Test
      run: ./gradlew cucumber
      
